version: '3.7'
services:
  app:
    build: .
    command: ['npm', 'start']
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
